# Generated by Django 3.2.8 on 2023-06-15 23:20

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='profile_images/avatar.jpg', upload_to='profile_images'),
        ),
    ]
