# Generated by Django 3.2.8 on 2023-05-28 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('property_type', models.CharField(choices=[('Complete House', 'Complete House'), ('Apartment', 'Apartment'), ('Self-Contained', 'Self-Contained')], max_length=20)),
                ('bedrooms', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5+')], max_length=2, null=True)),
                ('bathroom_type', models.CharField(choices=[('Self-contained', 'Self-contained'), ('General', 'General'), ('Private Detached', 'Private Detached')], max_length=20)),
                ('country', models.CharField(choices=[('Nigeria', 'Nigeria')], max_length=20)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('state_lga', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(default='avatar.jpg', upload_to='profile_images')),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realestate.agent')),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realestate.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.agent')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.landlord')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.prospect')),
            ],
            options={
                'verbose_name_plural': 'Tenancies',
            },
        ),
        migrations.AddField(
            model_name='prospect',
            name='properties',
            field=models.ManyToManyField(through='realestate.Tenancy', to='realestate.Property'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_reference', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.property')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.prospect')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.property')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.prospect')),
            ],
        ),
    ]
