# Generated by Django 3.2.8 on 2023-05-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='property',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='prospect',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tenancy',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='tenancy',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='tenancy',
            name='property',
        ),
        migrations.RemoveField(
            model_name='tenancy',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Landlord',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='Prospect',
        ),
        migrations.DeleteModel(
            name='Tenancy',
        ),
    ]
