# Generated by Django 3.2.8 on 2023-06-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_alter_property_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(choices=[('Inquiry', 'Inquiry'), ('Reinquiry', 'Reinquiry'), ('Payment', 'Payment')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
