# Generated by Django 3.2.8 on 2023-06-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_notification_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, max_length=220, null=True),
        ),
    ]
