# Generated by Django 3.2.8 on 2023-06-15 21:32

from django.db import migrations, models
import realestate.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_auto_20230610_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='profile_images/', validators=[realestate.models.AllowedFormatsValidator()]),
        ),
    ]
