# Generated by Django 3.2.8 on 2023-06-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0011_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(choices=[('Inquiry', 'Inquiry'), ('Reinquiry', 'Reinquiry'), ('Negotiation', 'Negotiation'), ('Payment', 'Payment')], max_length=20),
        ),
    ]
